name: Release
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash

jobs:
  changelog:
    name: Changelog PR or Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action/action-setup@v2.2.1
        with:
          version: ^7.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Change version
        run: pnpm version

      - name: Release package
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changesets release
          commit: "[ci] release"
          title: "[ci] release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
